@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTk0ODUzNTR9.7uL7R_ao9fVoiMMLjXB8Bd2uQMir_O8m29EEDISpx1s

POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

###
POST http://localhost:3000/users/groups

Content-type: application/json

{
  "name": "Ultimate"
}

###
GET http://localhost:3000/users/2
Authorization: Bearer {{jwt}}
Content-Type: application/json

###
GET http://localhost:3000/users/1/restaurants
Authorization: Bearer {{jwt}}